# Generated by Django 3.2.15 on 2023-08-31 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rivue_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rivue',
            name='ProImage',
            field=models.ImageField(default='C:\\Users\\anusr\\OneDrive\\Desktop\\milu.jpg', upload_to='images/'),
        ),
    ]
